version: '3.8'
services:
  geo-pg:
    image: postgres:14.1-alpine
    restart: always
    container_name: geo-pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geolocation
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  geo-api:
    build: .
    container_name: geo-api
    environment:
      - POSTGRE_HOST=geo-pg
      - POSTGRE_USER=postgres
      - POSTGRE_PASS=postgres
      - POSTGRE_DB=geolocation
    ports:
      - '8080:8080'
    depends_on:
      - geo-pg
volumes:
  db:
    driver: local
